# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from server_fllower_house.proto import HouseServer_pb2 as server__fllower__house_dot_proto_dot_HouseServer__pb2


class BroadcastStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateStream = channel.unary_stream(
                '/proto.Broadcast/CreateStream',
                request_serializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Connect.SerializeToString,
                response_deserializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.FromString,
                )
        self.BroadcastMessage = channel.unary_unary(
                '/proto.Broadcast/BroadcastMessage',
                request_serializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.SerializeToString,
                response_deserializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Close.FromString,
                )


class BroadcastServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CreateStream(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastMessage(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateStream,
                    request_deserializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Connect.FromString,
                    response_serializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.SerializeToString,
            ),
            'BroadcastMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastMessage,
                    request_deserializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.FromString,
                    response_serializer=server__fllower__house_dot_proto_dot_HouseServer__pb2.Close.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Broadcast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Broadcast(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CreateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.Broadcast/CreateStream',
            server__fllower__house_dot_proto_dot_HouseServer__pb2.Connect.SerializeToString,
            server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BroadcastMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Broadcast/BroadcastMessage',
            server__fllower__house_dot_proto_dot_HouseServer__pb2.Message.SerializeToString,
            server__fllower__house_dot_proto_dot_HouseServer__pb2.Close.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
